name: dockerloginDEVQA

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  Logintodockerhubdev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
       username: ${{secrets.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}
    - name: Docker Pull
      run: docker pull hello-world
    - name: Docker Tag
      run: docker tag hello-world jnirmal1/hello-world
    - name: Docker Push
      run: docker push jnirmal1/hello-world
  Logintodockerhubtest:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
       username: ${{secrets.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}
